# Generated by Django 5.2.15 on 2026-07-04 04:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_token", models.CharField(db_index=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="verified_badge_requires_approved_kyc",
        ),
        migrations.AlterField(
            model_name="user",
            name="country_code",
            field=models.CharField(
                db_index=True,
                max_length=2,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Country code must be ISO 3166-1 alpha-2 (e.g. US, NG).",
                        regex="^[A-Z]{2}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="handle",
            field=models.CharField(
                db_index=True,
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Handle must be 3–30 alphanumeric characters or underscores.",
                        regex="^[a-zA-Z0-9_]{3,30}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kyc_status", "approved"),
                    ("verified_badge", False),
                    _connector="OR",
                ),
                name="verified_badge_requires_approved_kyc",
            ),
        ),
        migrations.AddField(
            model_name="emergentsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emergent_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
